services:
    api:
        build: .
        ports:
            - "5000:5000"
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/library_db
        depends_on:
            - db
        volumes:
            - .:/app

    db:
        image: postgres:14
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=library_db
        ports:
            - "5430:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
